Algoritmo "EX_2"


Var
// Seção de Declarações das variáveis
   n1, n2, total : inteiro

Inicio

      // Entrada de dados
      escreva("Digite um numero: ")
      leia(n1)
      
      escreva("Digite um numero: ")
      leia(n2)
      
      // Processamento
      total <- n1 + n2
      escreval("Soma = ", total)
      total <- n1 - n2
      escreval("Subitração = ", total)
      total <- n1 * n2
      escreval("multiplicacao = ", total)

      
Fimalgoritmo