algoritmo "IDADE"

var
     // Declarar variavel
     idade : inteiro

inicio

      // Entrada de dados
      escreval("Qual sua idade? ")
      leia(idade)
      
      se( (idade >= 67) ) entao
         escreval("Parabéns, você já pode ser vacinado!")

      senão
         escreval("Aguarde sua vez para ser vacinado(A)")

      fimse
      
      
      escreval("Obrigado por acessar o sistema!")

fimalgoritmo